version: '2'
networks:
  public-network:
    external:
      name: proxy

services:
  web:
    image: swaggerapi/swagger-editor
    networks:
      - public-network
    expose:
      - 8080
    environment:
      VIRTUAL_HOST: swagger.dev
